readthedocs/recommonmark

- README.md
This prevents copying leading spaces.
> Unindent code examples in README.

- recommonmark/parser.py
https://github.com/rtfd/CommonMark-py/commit/280ec2cb0582cf4ed6da159b6d150557bd5a97f1 broke recommonmark
> Adapt to rename of DocParser in CommonMark

- recommonmark/parser.py
This ensures that source information will be passed down the tree
correctly by Node.setup_child
https://github.com/docutils-mirror/docutils/blob/master/docutils/nodes.py#L92
In turn, this means these nodes will be correctly picked up for gettext
output.
> [#21] Append nodes before appending their children

- README.md
The currently mentioned repo is abandoned and links to the new one.
> README.md: Link to the new CommonMark-py repository

- docs/auto_structify.md
- recommonmark/transform.py
I ran into an issue with using the `sidebar` directive with the ```eval_rst fenced blocks. This PR creates a shorthand syntax for rendered rst directives.
``` sidebar:: Sidebar title
:caption: A caption
The sidebar content
```
The detects the presence of double colons and renders them as directives rather than code-blocks. It also parses the directive nodes in a new document which fixes the rendering of sidebars. I am not sure if any other directives than sidebar that were previously broken and are now fixed.
Includes updated documentation for this as well:
> Improve rst_eval

- recommonmark/transform.py
This PR fixes issue #39.
**History**
I've been working on a project where I had to build docs with `Sphinx` and `markdown`.
The TOC wasn't building on `Windows` but was on `Linux`.
So this lead me to conclude it was an environment issue.
Upon debugging `Sphinx` I found that it was comparing the `found_docs` with the `docname` and in Windows the path didn't match due to the path separator.
Debugging `recommonmark` I found that in `tranform.py` `parse_ref` the `relpath` follows environment specs but `Sphinx` awaits the `relpath` to be in `Unix` format.
**About**
The submitted code fixes this issue. It's been tested on `Windows` and `Linux`.
Personally, I'm fairly new with `Python`, so if you happen to know a better way to resolve this issue, feel free to reject this PR, but please fix this …
> Added path separator handler for non-Unix environment.

- recommonmark/__init__.py
This way, it can be simply enabled like this (in `conf.py`):
```python
extensions = ['recommonmark']
```
Note, however, that this only works for Sphinx version >= 1.4 because it uses [add_source_parser()](http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_source_parser).
> Turn package into a Sphinx extension

- recommonmark/parser.py
- recommonmark/transform.py
- requirements.txt
- tests/sphinx_code_block/conf.py
- tests/sphinx_code_block/index.md
- tests/sphinx_custom_md/conf.py
- tests/sphinx_custom_md/index.markdown
- tests/sphinx_indented_code/conf.py
- tests/sphinx_indented_code/index.md
- tests/test_sphinx.py
- tox.ini
This adds a configuration variable `commonmark_suffixes` where the user can specify which files with which extensions the AutoStructify transform will apply to. This is because I have markdown files that have endings other than '.md'.
> Transform files with other endings besides .md

- recommonmark/transform.py
At the moment it is passing source as node.rawsource.  This is always
going to be the empty string as it is getting it from a newly created
node.
This patch saves a reference to the original node and parses down the
correct source.  This patch along with #52 means that eval_rst blocks will
internationalize correctly fixing [#47].  Sphinx will not translate
nodes with a blank source.
Also relative paths will now work within eval_rst blocks.
> Fix eval_rst so it assigns source properly

- README.md
- recommonmark/parser.py
- requirements.txt
- tests/sphinx_xref/conf.py
- tests/sphinx_xref/index.md
- tests/sphinx_xref/link.md
- tests/test_sphinx.py
By using `pending_xref` for links, sphinx will resolve links, which works better then trying to duplicate the logic.
> Use pending_xref for links

- README.md
The links are hard to find, so this makes them more discoverable. On the RTD site, the autostructify link doesn't show as a clickable link, making it really hard to find:
This makes that link a proper link so it shows up in the page, and adds a short paragraph at the beginning of the section mentioning the existence of the autostructify docs
> Updating autostructify links in readme

- recommonmark/parser.py
- tests/test_basic.py
Sphinx 1.6.5 with tip recommonmark hard errors when a markdown document contains a cross-reference to another local markdown document as it unconditionally access the `refdomain` of a `pending_xref`. This was fixed [elsewhere](https://github.com/ignatenkobrain/sphinxcontrib-issuetracker/pull/13/files#diff-61beda6e59ec3020dbf0c2826dbb64c4R161) by setting it to `None`. This patch uses the same approach which no longer causes the Sphinx build to fail on cross-linking a markdown document however the generated link is not correctly rendered producing broken links in the generated html.
Addressing the broken links, the `mdnode.destination` is stripped of its file extension if that extension is supported by `CommonMarkParser` however this will only work for markdown documents, not …
> Fix hard error on cross-linking markdown document

- recommonmark/parser.py
- tests/test_basic.py
Return default line number of 0 when no sourcepos found.
Fixes #100
> Fix exception with link inside bold/italic

- recommonmark/parser.py
When section name is not written in ASCII, the ID of the section will be
generated by default, in the form of 'id<unique number>'. This is no good
writing links to other document, whose ID are subject to change in adding
or removing sections.
Adding a `translate_section_name` filter in Parser will allow user to install
a customized one to translate the section name into more readable one. For
example, convert the Chinese section name to more ASCII-friendly pinyin.
> Add section name translate support

- setup.py
Add a description, URL and license to `setup.py` so [the recommonmark package page on PyPI](https://pypi.org/project/recommonmark/) will include that information.
> Add more metadata to setup.py for PyPI

- recommonmark/parser.py
- tests/test_basic.py
Fixes "ImportError: No module named CommonMark" as proposed in [rtfd/recommonmark#116](https://github.com/rtfd/recommonmark/issues/116#issue-358019182)
> rename `CommonMark` to `commonmark`

- recommonmark/parser.py
- tests/test_basic.py
Without this any html_block nodes processed by the parser are dropped.
`visit_html_block` uses the existing logic for `visit_html_inline`.
Added a test case to check html_blocks are parsed as expected.
Fixes: https://github.com/rtfd/recommonmark/issues/121
> Add visit_html_block

- setup.py
In #118, there was a change made to rename all commonmark imports from `commonmark` to `CommonMark` due to a breaking change to the package name in that dependency in version 0.8.1. However, the dependency on `commonmark` wasn't updated, which means that people pulling in commonmark >= 0.7.3 and < 0.8.1 are experiencing issues while using recommonmark. This updates the versioned dependency accordingly to resolve this issue.
> Bump dependency on commonmark to >= 0.8.1

- recommonmark/parser.py
- tests/sphinx_generic/index.md
- tests/test_basic.py
- tests/test_sphinx.py
The current [RecommonMark specification on images](https://spec.commonmark.org/0.28/#images) says that:
should render as
<p><img src="/url" alt="foo" title="title" /></p>
which means that "foo" should be the `alt` attribute, and "title" should be the `title` attribute.
Currently, `recommonmark` will:
1. set the `alt` attribute to "title"
2. render "foo" as literal text following the image element.
Neither yields results in line with the RecommonMark standard, resulting in the following when transformed to HTML:
<p><img src="/url" alt="title" />foo</p>
While it might be surprising that `alt` is set to "title", the more pressing issue is how the alt text becomes literal text within the paragraph, typically not rendering well.
This pull request instead makes `recommonmark`:
1. set the `alt` …
> Use image description text as "alt", drop title

- README.md
- recommonmark/parser.py
- recommonmark/transform.py
- tests/test_basic.py
Fixes: https://github.com/readthedocs/recommonmark/issues/165
> Add `accepted_url_schemes` option to allow toplevel refs

- README.md
- recommonmark/transform.py
This adds the 'auto_toc_maxdepth' config option (defaults to 1) that
will set the max depth for the auto-generated table of contents.
> Allow the Auto TOC maxdepth to be configurable.

- recommonmark/parser.py
- tests/sphinx_generic/index.md
- tests/test_sphinx.py
Hi,
This PR fixes the erroneous handling of external links to 'supported' files.
Until now, the extension of _every_ supported type has been stripped.
Adding an additional check ("if not scheme_known") was sufficient to avoid doing this for external links.
**Example:**
A link to http://example.com/README.md will point to http://example.com/README without this fix, since 'md' is a supported type.
**Example 2:**
Simply linking to this project's README file is impossible at the moment: 
https://github.com/readthedocs/recommonmark/blob/master/README.md becomes https://github.com/readthedocs/recommonmark/blob/master/README, which of course doesn't exist.
> Bugfix: External links to 'supported' files lose their file extension
